### ISSUE TITLE
Agent_ids

### ISSUE THREAD

**Issue by mahdi91** [ChuaCheowHuan/gym-continuousDoubleAuction#36]
Hi, 
I am trying to run "CDA_NSP", but I get this error
**"The element returned by reset() has agent_ids that are not the names of the agents in the env. 
Agent_ids in this MultiAgentDict: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Agent_ids in this env:[]. 
You likley need to add the private attribute `_agent_ids` to your env, which is a set containing the ids of agents supported by your env."**

I am new to rllib, I do not know what to do to solve it.

**Comment by ChuaCheowHuan** [comment]
Hi, 

I can't reproduce your error. I suspect it could be some version mismatch with the main dependencies.

I'll recommend running the notebook in Google Colab.  You'll need a copy of the repo in your google drive. You should have the repo in the `My Drive/Colab Notebooks` folder. Once, you have that ready, open up the notebook in Colab and follow the steps below:

1) Uncomment the following lines in the first cell in the notebook:
```
# !pip install -r requirements.txt

# !pip install tensorflow==2.2.0
# !pip install ray[rllib]==0.8.5
```
2) Run ONLY the first cell. When it's done, goto `runtime` tab, click `restart runtime`. This should install all the correct versions of the required dependencies.

3) In the third cell, change the values of the variables as shown below:
```
# Change to smaller values to reduce memory usage in Colab.
num_agents = 4
num_trained_agent = 1

# Set to False to disable loading of weights.
is_restore = False
```

4) goto `runtime` tab, click `run all`

That works for me.
I hope that helps.

**Comment by mahdi91** [comment]
Hi, sorry for my late response.
Thanks for your help,
You are right, it works in Colab notebook.

Best,
Mehdi
